### ISSUE TITLE
'Could not log in' - 403 (FORBIDDEN)

### ISSUE THREAD

**Issue by misterbauer** [metasys-server/historian#4]
I have an NAE55 set up as the site director running Metasys 10.1, but I am obviously missing something, because running the QuickExtract app only results in "Could not log in: The Host, Username, and Password combination did not work, please try again!"

I'm simply running it on my local network, and my command is:
`dotnet run --host 10.1.0.120 --username <Metasys Username> --password <Metasys Password>`

In addition, I get a 403 forbidden if I POST my Metasys credentials to the login endpoint (https://10.1.0.120/api/v2/login) as well.

Can you help point me in the right direction to determine where I'm going wrong?

**Comment by ghost** [comment]
The Metasys REST API is only supported on Metasys server products. It is not available on Metasys NAEs at this time.
